apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
        app: demo
  replicas: 3
  template:
    metadata:
        labels:
            app: demo
    spec:
        containers:
          - name: demo
            image: docker.io/library/demo:1.0
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8080

